export const SPY_WORDS = [
  'airport',
  'amusement park',
  'aquarium',
  'art museum',
  'bakery',
  'bank',
  'barber shop',
  'basketball court',
  'beach',
  'bookstore',
  'bowling alley',
  'bus stop',
  'cafe',
  'campground',
  'castle',
  'cemetery',
  'cinema',
  'classroom',
  'coffee shop',
  'construction site',
  'cruise ship',
  'dentist office',
  'desert island',
  'doctor office',
  'factory',
  'farm',
  'fire station',
  'flower shop',
  'football stadium',
  'forest',
  'gas station',
  'gym',
  'hair salon',
  'hospital',
  'hotel lobby',
  'ice cream shop',
  'internet cafe',
  'jail',
  'kitchen',
  'library',
  'lighthouse',
  'mountain cabin',
  'movie set',
  'museum',
  'night club',
  'office',
  'opera house',
  'park',
  'pet store',
  'pharmacy',
  'playground',
  'police station',
  'post office',
  'restaurant',
  'school bus',
  'shopping mall',
  'ski resort',
  'space station',
  'sports bar',
  'subway station',
  'supermarket',
  'swimming pool',
  'taxi',
  'train station',
  'university',
  'veterinary clinic',
  'wedding',
  'zoo',
] as const

export function pickRandomSpyWord(): string {
  const i = Math.floor(Math.random() * SPY_WORDS.length)
  return SPY_WORDS[i] ?? 'library'
}

export function normalizeSpyGuess(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, ' ')
}

