const PROMPTS: string[] = [
  'When you realize it’s Monday again…',
  'POV: You opened the group chat after one hour.',
  'That moment you remember you forgot to save your work.',
  'When the Wi‑Fi disconnects during the final boss fight.',
  'Me pretending I didn’t see the notification.',
  'When the food arrives and everyone suddenly stops talking.',
  'You said “just one more episode” and now it’s 3 AM.',
  'When the teacher says “this will be on the test.”',
  'When you hit “send” and instantly regret it.',
  'When you get paid and your bank account still looks the same.',
  'When your code works on the first try (suspicious).',
  'When your friend says “I’m on my way” but they’re still at home.',
  'When you confidently walk into the wrong meeting and still sit down.',
  'When your alarm goes off and your body says “absolutely not.”',
  'When you open the fridge for the 5th time expecting new food.',
  'That face you make when someone says “quick question” at 4:59 PM.',
  'When the “free trial” ends and your app suddenly has “features.”',
  'When you say “I’ll be there in 5” and you’re still in a towel.',
  'When you try to be productive and your brain launches 27 tabs instead.',
  'When you finally remember the thing you forgot… two days later.',
  'When you hear your name in a conversation and you weren’t listening.',
  'When you wave back but they weren’t waving at you.',
  'When you hit “reply all” and immediately see your life flash.',
  'When you realize the “mute” button was not actually on.',
  'When you join the call and your camera chooses violence.',
  'When you leave the house and forget how to act in public.',
  'When you say “no worries” but you are, in fact, worries.',
  'When you try to whisper and your voice cracks like a cartoon door.',
  'When you open the front camera by accident and get jump-scared.',
  'When you remember something embarrassing from 2014 at 2 AM.',
  'When the cashier says “enjoy” and you say “you too.”',
  'When you find a new song and play it 48 times in a row.',
  'When the playlist shuffles into emotional damage at full volume.',
  'When someone says “be yourself” and you’re like… which one?',
  'When you try to look busy and accidentally become busy.',
  'When you type “lol” but your face is stone.',
  'When you try to take a nap and wake up in a new timeline.',
  'When you’re “just resting your eyes” and miss three hours.',
  'When the package says “delivered” and your porch says “no.”',
  'When you check tracking every 12 minutes like it’s a sport.',
  'When you learn the hard way what “final_final_v3” means.',
  'When you close the wrong tab and it was the one with the answer.',
  'When the app asks to update and you don’t trust it anymore.',
  'When your phone is at 3% and suddenly time moves faster.',
  'When you plug it in and it’s not charging (betrayal).',
  'When the elevator door closes and you remember one more thing.',
  'When you rehearse a joke all day and nobody gives you the opening.',
  'When you finally speak up and everyone talks over you at once.',
  'When the “one email” turns into a whole questline.',
  'When the printer makes that sound like it’s summoning something.',
  'When the “simple form” has 14 required fields.',
  'When you click “forgot password” and see your own reflection.',
  'When you get a notification and forget it before unlocking your phone.',
  'When you try to be mysterious but you’re just awkward.',
  'When you laugh at the wrong part because you’re anxious.',
  'When you open the chat and instantly regret being perceived.',
  'When you send a risky message and throw your phone across the room.',
  'When autocorrect exposes you in 4K.',
  'When you turn off autocorrect and now you can’t spell anything.',
  'When you start cooking and suddenly become a scientist.',
  'When the recipe says “season to taste” and you have no taste.',
  'When you taste the sauce and it tastes… like effort.',
  'When you add garlic and your ancestors start clapping.',
  'When you open a bag of chips and it’s 70% air (inflation).',
  'When you try to eat healthy and a cookie looks at you.',
  'When you buy salad ingredients and they expire as a group.',
  'When you say “I’m going to bed early” and then open the internet.',
  'When your pillow feels different and you start negotiating with it.',
  'When you can’t sleep because your brain starts a podcast.',
  'When you finally fall asleep and your neighbor chooses drums.',
  'When you see someone running and instantly assume danger.',
  'When you hear your stomach growl in a silent room.',
  'When you trip but pretend it was choreography.',
  'When you try to fix your posture and become a mannequin.',
  'When you stand up too fast and meet the shadow realm.',
  'When you make eye contact with the security camera.',
  'When you are the “adult in the room” and you’re the room.',
  'When you open your bank app and it opens a horror movie.',
  'When you remember subscriptions exist.',
  'When you cancel a subscription and it asks “why?” like it’s personal.',
  'When your card declines and the machine says it out loud.',
  'When you check your email and it’s just newsletters fighting.',
  'When you send a calendar invite and become the villain.',
  'When someone says “circle back” and you levitate with anger.',
  'When the meeting could have been a message but became a saga.',
  'When you say “I can take that” and now you own it forever.',
  'When someone says “we need a volunteer” and you suddenly can’t see.',
  'When the group project chooses you as the group.',
  'When your teammate says “I’ll start now” on the due date.',
  'When you ask for feedback and receive a novel.',
  'When you ask for help and receive “have you tried…” (yes).',
  'When you fix one bug and three more spawn.',
  'When you deploy and immediately start praying.',
  'When production is down and your coffee is also down.',
  'When you realize you’ve been debugging the wrong thing for an hour.',
  'When you add one console log and feel like a detective.',
  'When you remove the console logs and everything breaks again.',
  'When “works on my machine” becomes a personality trait.',
  'When you update one dependency and the whole app gets dramatic.',
  'When you see “breaking changes” and feel the break in your spirit.',
  'When you think it’s cached but it’s actually cursed.',
  'When you clear cache and it still remembers the trauma.',
  'When you refresh and the bug politely returns.',
  'When you open DevTools like it’s a ritual.',
  'When you copy-paste code and it gains new problems.',
  'When you read your own code from last month like it’s ancient ruins.',
  'When the “temporary” hack becomes a permanent landmark.',
  'When you push a commit and remember the typo in the message.',
  'When you hit merge and the conflicts start a new season.',
  'When the build fails and the error message is poetry.',
  'When you finally pass CI and don’t trust the silence.',
  'When you run tests and the tests run you.',
  'When the game says “press any key” and you panic.',
  'When you skip the tutorial and immediately regret your confidence.',
  'When the boss has a second phase (unfair).',
  'When you pause the game and the music still stresses you out.',
  'When your controller battery dies at the worst possible moment.',
  'When the lobby says “one more match” and it’s 2 hours later.',
  'When you queue with friends and instantly become the coach.',
  'When you say “I’m warmed up” after losing the warm-up.',
  'When you miss one shot and apologize to the whole team.',
  'When you win and suddenly you’re a strategist.',
  'When you lose and suddenly you’re a philosopher.',
  'When you open the app “for one thing” and forget your purpose.',
  'When you go online for answers and find more questions.',
  'When you watch a “quick tutorial” and it’s 42 minutes.',
  'When someone says “it’s easy” and you know it’s not.',
  'When you try to learn a new skill and your ego leaves.',
  'When you finally understand… and then forget instantly.',
  'When you walk into a room and the mission resets.',
  'When you say “I’m fine” in a tone that is not fine.',
  'When you try to be chill but your eyebrow betrays you.',
  'When you try to act natural and become suspiciously natural.',
  'When you’re late and every red light becomes personal.',
  'When you leave early and still arrive late (how).',
  'When your GPS says “make a U-turn” like it’s judging you.',
  'When you miss the exit and pretend it was your plan.',
  'When you parallel park and the whole street watches.',
  'When you sit in the car after arriving and just… decompress.',
  'When someone says “we need to talk” and your soul exits.',
  'When you say “no pressure” and add pressure anyway.',
  'When you try to be supportive but accidentally roast them.',
  'When you try to roast them but accidentally confess feelings.',
  'When you clap back in your head and stay silent in real life.',
  'When you think of the perfect comeback… tomorrow.',
  'When you take a selfie and your phone humbles you.',
  'When you find your angle and become unstoppable.',
  'When the lighting is good and you start believing in yourself.',
  'When the lighting is bad and you start believing in legends.',
  'When you wear a new outfit and suddenly you’re the main character.',
  'When you wear sweatpants and suddenly you’re a couch entity.',
  'When you step on a LEGO and see all your choices.',
  'When you drop something and it teleports under the couch.',
  'When you look for your keys while holding your keys.',
  'When you open the wrong door and commit anyway.',
  'When you say “watch this” and it immediately fails.',
  'When you try to be smooth and become a slide whistle.',
  'When you join a trend late and everyone moved on.',
  'When you say “I don’t care” and then care intensely.',
  'When you tell yourself “don’t overthink it” and then overthink it.',
  'When you rehearse a conversation and it goes off-script instantly.',
  'When you finally set boundaries and people discover consequences.',
  'When you do self-care and it looks like staring at a wall.',
  'When you do “a quick clean” and reorganize your whole life.',
  'When you vacuum and find a lost era under the bed.',
  'When you do laundry and lose one sock to the void.',
  'When you find the missing sock and it’s with another family.',
  'When you try to fold a fitted sheet and accept defeat.',
  'When you buy a planner and your life says “cute.”',
  'When you start journaling and it becomes dramatic.',
  'When you finally drink water and feel reborn for 12 minutes.',
  'When you order food and forget you ordered food.',
  'When the delivery arrives and your dog becomes security.',
  'When the doorbell rings and you become a statue.',
  'When you say “come in” and they actually come in.',
  'When you say “we should hang out” and it becomes a contract.',
  'When you try to schedule with friends and it’s like diplomacy.',
  'When everyone’s calendars align once every eclipse.',
  'When you host and realize you have no cups (adulting).',
  'When you go out and immediately miss your bed.',
  'When you get home and your bed feels like a luxury resort.',
  'When you step outside and the weather has plot twists.',
  'When you bring an umbrella and it doesn’t rain (power move).',
  'When you don’t bring an umbrella and it monsoons (lesson).',
  'When you put on headphones and the world becomes manageable.',
  'When you take off headphones and reality is loud.',
  'When someone says your name twice and you know it’s serious.',
  'When your pet acts innocent and you know something happened.',
  'When your cat knocks something over and makes eye contact.',
  'When your dog hears the word “walk” and achieves flight.',
  'When you try to take a cute pet photo and they choose chaos.',
  'When you open your camera and the pet becomes a blur.',
  'When you spill something and your brain goes into slow motion.',
  'When you try to clean it and make it worse (tutorial needed).',
  'When you finally clean it and discover it was sticky forever.',
  'When you say “I’ll remember this” and you absolutely won’t.',
  'When you set a reminder and then ignore the reminder.',
  'When you snooze the reminder like it offended you.',
  'When you decide to “get your life together” at midnight.',
  'When you start a new routine and day 2 arrives.',
  'When you do one healthy thing and expect a trophy.',
  'When you stretch once and feel like an athlete.',
  'When you see someone jogging and respect them from afar.',
  'When your brain says “let’s over-share” and your mouth agrees.',
  'When you try to be quiet and your chair announces you.',
  'When you’re the only one laughing and you commit anyway.',
  'When you say “I’m not competitive” and then become competitive.',
  'When you lose and suddenly the rules matter.',
  'When you win and suddenly the rules are perfect.',
]

export function hashSeed(s: string) {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
  return h
}

export function pickTwoPrompts(seed: string): [string, string] {
  const n = PROMPTS.length
  const a = Math.abs(hashSeed(seed)) % n
  const b = (a + 1 + (Math.abs(hashSeed(seed + ':b')) % (n - 1))) % n
  return [PROMPTS[a], PROMPTS[b]]
}

export function tieBreakIndex(seed: string, round: number) {
  return (Math.abs(hashSeed(`${seed}|${round}|ctx`)) % 2) as 0 | 1
}
